### ISSUE TITLE
authfile path should respect pam.d configuration

### ISSUE THREAD

**Issue by ultrabug** [maximbaz/yubikey-touch-detector#1]
https://github.com/maximbaz/yubikey-touch-detector/blob/33dad60850fba18ab4424ba3430ed532af8b5850/detector/u2f.go#L15

The auth_file path is hard written but should instead use the `authfile` configuration option of the pam_u2f module

Took me a little while to understand why your project didn't work for me :)

Thanks!

**Comment by maximbaz** [comment]
Thanks 🙂

I'm not sure how to query the pam.d configuration, this path can be set in any file... Do you have some ideas? For example, in my case I have the definition in `/etc/pam.d/sudo`, but it can be anywhere based on what user configured...

Alternatively I can make this path configurable via CLI argument or some config file.

**Comment by ultrabug** [comment]
I'd go for a CLI argument since parsing /etc/pam.d/ folder looks tedious and you'd have to worry about multiple authfile configurations (madness)

**Comment by maximbaz** [comment]
`--u2f-keys-path` (as well as `--gpg-pubring-path`) are available in v1.0.2 👍
