### ISSUE TITLE
Feature request: Close notification when touch is detected

### ISSUE THREAD

**Issue by n-st** [maximbaz/yubikey-touch-detector#12]
The program already detects when a touch is no longer required (e.g. `[notifiers/stdout] GPG_0`).
libnotify supports [closing notifications](https://unix.stackexchange.com/questions/75386/clearing-modifying-previous-libnotify-notifications) (by storing a reference to the notification when it is created), so it might be possible to retract the notification when the button has been touched.

**Comment by maximbaz** [comment]
Good idea, would you like to try to submit a PR? I don't use libnotify feature personally, but would gladly review and merge if you send one 🙂 

Right now the code basically invokes `notify-send`:

https://github.com/maximbaz/yubikey-touch-detector/blob/6ff3ff0225d23d8922c1bf74c1fdf6804e20db02/notifier/libnotify.go#L10-L12

As far as I know, this approach doesn't give you any sort of notification ID that can later be used to close a notification.

I would recommend either looking at some Go libraries that provide proper libnotify interface, or maybe do this via DBUS like described [here](https://unix.stackexchange.com/a/75411)?

**Comment by n-st** [comment]
Here's an attempt at implementing the change. My first time writing Go code, so it will probably need some polishing. ;)

Unfortunately, there seem to be only two libnotify bindings for Go, both of which aren't exactly *fresh*…
[mqu/go-notify](https://github.com/mqu/go-notify) (2013) seems to be incompatible with the current version of go-glib and fails to compile.
[menefotto/go-libnotify](https://github.com/menefotto/go-libnotify) (2016) compiles with my Go 1.14.4, but uses some sort of custom wrapper to replace go-glib, through which I can't distinguish between an actual error and a wrapped `nil` error…

I wanted to avoid the additional dependency on dbus (though libnotify might use it in the background), so I'm going with menefotto/go-libnotify for now.

Things we should probably check:
- Is there really no way to unwrap and check the error from `Show()`/`Close()` or am I just misunderstanding Go?
  (`fmt.Printf("%#v\n", err)` prints it as `&notify.Error{GError:(*notify._Ctype_struct__GError)(nil)}`.)
- The Makefile automatically added the new library to two dependency files — I assume that's okay/intentional?
- I only generate a single notification object and show/close it as appropriate. Works fine with the `dunst` OSD service, but maybe other services don't re-show notifications that existed previously? Could probably wait and see if anyone actually runs into a problem there.

**Comment by ckotte** [comment]
Any idea why this doesn't work on GNOME?

```notify-send "YubiKey is waiting for a touch"``` works, but ```libnotify.NotificationNew()``` doesn't show any notification.

I also tried v1.7.1 with notify-send and this also doesn't show me any notification!?

**Comment by maximbaz** [comment]
Do you also reproduce the absence of notifications when you run `$ yubikey-touch-detector --libnotify` from a terminal, as a regular user?

My only guess is that if it runs in some weird/restricted environment, the app doesnt have access to UI, like you know those old stories with `$DISPLAY` variable https://askubuntu.com/questions/771715/setting-display-0-has-no-effect-to-notify-send-via-ssh

**Comment by ckotte** [comment]
Yes, I tested it manually. I use GNOME and Wayland. 

Not sure why, but now it works after I rebooted my system.

**Comment by myelsukov** [comment]
Damn, guys, you broke my nice notifications accompanied with sound. I can't use my custom notification script anymore :(((
There's a famous proverb: "The best is the enemy of the good"

**Comment by n-st** [comment]
Did you replace `notify-send` with your custom script? That's, uhm, _creative_. 😄

If you're going to use a custom notification anyway, you can attach your script to the `unix_socket` notifier and listen for GPG_1/GPG_0 events (more details in the readme).

Let us know if that fits your use case. :)

**Comment by maximbaz** [comment]
Haha 😄 

I agree with @n-st, just take [this script](https://github.com/maximbaz/dotfiles/blob/master/bin/waybar-yubikey) and replace the `printf` calls with whatever you like, the second `printf` is triggered when yubikey begins to wait for a touch (show notification, play music), and the first one is triggered when it stops waiting for a touch.

**Comment by myelsukov** [comment]
> Did you replace notify-send with your custom script? That's, uhm, creative. ;)

That was @maximbaz suggested to do when I discussed this topic with him.

Now, seriously, why would anyone want to build, debug and deploy (systemd?) their own listening service if the only thing they want is executing some code upon notification? Why `yubikey-touch-detector` can't just execute that user specified payload and pass all needed information to it hence let the user to avoid all that hassle? It's so much easier to use!

> I agree with @n-st, just take this script 
@maximbaz  with all due respect to your opinion I will have to fork this repo and make `yubikey-touch-detector` the notification service I need without creating a new one :) Many big thanks for providing this possibility to me :grin:

**Comment by maximbaz** [comment]
A basic script that will listen on unix socket and execute some action is literally 3 lines of shell script code, it's hard to get simpler than that 🙂 At the same time this API allows to build any kind of integrations, you can achieve a lot more than with just calling a user-provided script.

However I acknowledge that it's just my opinion, and I'm very happy that you are able to take the code and adapt it to your own needs! Feel free to ping me if you need any guidance 🙂

**Comment by myelsukov** [comment]
> A basic script that will listen on unix socket and execute some action is literally 3 lines of shell script code

The script, yes. But it is not a script. It is a user service that has to be started when user logs in. It should be started exactly one time. It should be stopped when user logs out. User should be able to check its status and restart if needed. 

I already have that service. It called `yubikey-touch-detector`. Why on the earth would I need another one? When my notification stopped working what should I look at? `yubikey-touch-detector` or my service? Both?
If I would have needed something sophisticated then I would go with you suggestion, but I _do_not_need_sophistication_.
OK, I know how to implement systemd units but I will _not_ do it. I don't need another moving part that needs my attention and can break.

I treat `yubikey-touch-detector` as a utility, not as a framework. Unfortunately it can't be used as a framework. If it would have been implemented similarly to [pydev](https://github.com/pyudev/pyudev) then I would have implemented my own service using it. And I still would have _one_ service instead of _two_.

**Comment by maximbaz** [comment]
oh but it can be used as a framework, check how barista is doing it, and you will have exactly one service 🙂 

https://github.com/soumya92/barista/blob/main/samples/yubikey/yubikey.go

**Comment by myelsukov** [comment]
You missed the part where I said that I need just one very simple thing (that was implemented in the previous version). I still want to avoid writing and supporting a service 😁
