### ISSUE TITLE
GPG_1 and endless loop when no Yubikey is plugged in

### ISSUE THREAD

**Issue by n-st** [maximbaz/yubikey-touch-detector#15]
We're not quite done with the hacks yet… :confused: 

When I select an email (even an unencrypted one) in Thunderbird (v68 with Enigmail) *without my Yubikey plugged in*, the touch detector enters an infinite loop of generating "waiting for a touch" notifications (several per second).

`-v` shows that it gets stuck at `GPG_1` (the loop of notifications has no individual logging, so doesn't show up of course).
Version 1.7.1 simply sent one to three pairs of `GPG_1` + `GPG_0` in the same second, then stayed quiet until I selected another email.

**Comment by n-st** [comment]
`gpg --card-status` returns exit code 2 when no card is connected (tested, since there seem to be no details beyond "return […] other error codes for fatal errors" in the man page).
We could probably use that exit code to distinguish between "killed while waiting for card" and "no card connected at all", and avoid the "waiting for a touch" notification when there is no card connected. (As far as I see, "waiting" detection should still sort-of work even if no card is connected, because card access attempts would still queue up and cause the timeout we are checking for. The timeout might technically also indicate "waiting for Yubikey to be inserted, signing doesn't require touch", but I think that's close enough.)

**Comment by maximbaz** [comment]
Once again, nice catch! 👍 

Your approach is good, although I chose to revert the logic, Go  reports exit code as `-1` if the process was killed, so we can just check for that.

Could you please give it a test?

**Comment by n-st** [comment]
7b294ed works as intended, thank you for the quick fix! :)
