### ISSUE TITLE
Environment variables don't work / further clarification necessary

### ISSUE THREAD

**Issue by ckotte** [maximbaz/yubikey-touch-detector#17]
How do I have to put the environment variables into ```$HOME/.config/yubikey-touch-detector/service.conf```?

```
YUBIKEY_TOUCH_DETECTOR_LIBNOTIFY
YUBIKEY_TOUCH_DETECTOR_VERBOSE
``` 
or
```
$YUBIKEY_TOUCH_DETECTOR_LIBNOTIFY
$YUBIKEY_TOUCH_DETECTOR_VERBOSE
```

doesn't work

**Comment by maximbaz** [comment]
You have to provide a value, either one of `true`, `yes` or `1` will be accepted:

```
YUBIKEY_TOUCH_DETECTOR_LIBNOTIFY=1
YUBIKEY_TOUCH_DETECTOR_VERBOSE=yes
```

Will add to README, thanks for pointing out 🙂

**Comment by ckotte** [comment]
Does this only work with the systemd service or also if I execute it manually? It doesn't show me verbose output if I execute it manually. I cannot verify if libnotify variable works with the systemd service because libnotify doesn't work with GNOME on my side.

**Comment by ckotte** [comment]
Ok. I checked the unit file. ;)

**Comment by maximbaz** [comment]
that file specifically is for systemd service only, it is loaded here:

https://github.com/maximbaz/yubikey-touch-detector/blob/015dda0ea3fcee37e16c25f9420927ee033556cc/yubikey-touch-detector.service#L6

But in general you can define such environment variables wherever you normally place them, like in /etc/profile. As long as the variables are exported and the process can see them, they will be respected 🙂

**Comment by hyx0329** [comment]
For GNOME users, you might need a custom ".desktop" file like this one:

```
[Desktop Entry]
Exec=/usr/bin/yubikey-touch-detector --libnotify
Name=Yubikey Touch Detector
GenericName=Yubikey Touch Detector
Comment=Notify when yubikey need a touch.
StartupNotify=false
Terminal=false
Type=Application
Categories=Utility;
Keywords=Yubikey;FIDO;PGP;
```

then place it at `$HOME/.config/autostart/`
