### ISSUE TITLE
Desktops supported

### ISSUE THREAD

**Issue by gedw99** [maximbaz/yubikey-touch-detector#2]
I assume this only support Linux ?
I need MAc and Windows support to make it work with my desktop apps

**Comment by maximbaz** [comment]
I believe it can only work on Linux. Definitely not on Windows, maaaaybe it is possible to make it work on Mac, but I don't know for sure and I won't be to investigate as I don't own Mac (let me know if you want to investigate, I'll give you some tips and directions).

The thing is, this project is basically a bunch of hacks that are experimentally "proven to work", but they are _very_ fragile. U2F implementation depends on `pam-u2f` project (which I don't think exists on Windows, not sure about Mac), SSH and GPG detections depend on listening to file system events and counting how many times some files are being opened by unknown processes.

Closing as non-actionable for me, but as I said, if you want to investigate further if Mac can be supported, let me know.
