### ISSUE TITLE
Help - parse socket output and send to IPC

### ISSUE THREAD

**Issue by weilbith** [maximbaz/yubikey-touch-detector#20]
Hey,
thanks for this great tool!
There are already a couple of status bars supported. I now like to make it work with [polybar](https://github.com/polybar/polybar) as well. The idea is pretty simple, connect to the socket of `yubikey-touch-detector`, parse output for each event and covert it into messages that you can put onto a FIFO. This makes use of polybars custom modules via IPC ([short docs here](https://github.com/polybar/polybar/wiki/Module:-ipc). The component would look like that:

```dosini
[module/yubikey-touch]
type = custom/ipc

hook-0 = echo
hook-1 = echo "key-icon"

format-foreground = #ffffff
format-background = #ff0000
```

So when hook `0` (which is the initial one) gets triggered the component is empty, end for hook `1` it shows a nice icon and has catchy colors.
Now I need to listen to the output of the socket. When it matches `GPG_1`, `U2F_1` or `MAC_1` it should trigger hook `1` and when  `GPG_0`, `U2F_0` or `MAC_0` trigger hook `0`. 
My approach was like this `ncat --recv-only --unixsock $XDG_RUNTIME_DIR/yubikey-touch-detector.socket | grep 0 | polybar-msg hook yubikey-touch 1` (and the same for `1`).
Anyways, while I can listen to the socket and read the output successfully. But the `grep` does not work anymore. I guess because `grep` works on lines. So I tried the stream editor and also attempt to parse the number to make it re-used for the hook number: `ncat --recv-only --unixsock ./yubikey-touch-detector.socket | sed -r 's/GPG_([0,1])/\1/g'`. But that does not work as well. 

I'm sorry to bother you with such issues, but do you have some hints how to do this?

PS:
The idea was to make this then a systemd service unit that is triggered by your socket unit and gets the socket passed as template argument.

**Comment by maximbaz** [comment]
Hey! Happy to hear that you like the tool, and that you are building an extension for polybar - once you succeed, let's link to it in this project's README!

As to your question, what if you would read each message individually, parse it and then decide on the action - basically like I do in [waybar module](https://github.com/maximbaz/dotfiles/blob/master/.local/bin/waybar-yubikey)?

**Comment by weilbith** [comment]
Perfect that was the hint I needed. Sorry that I missed that. I looked into the Python bar implementation, but not waybar.
Alright, so I have a solution up and running. It is kinda hard to link it. But I could at least share it here as comment. Eventually I could make it a Gist that you can link. :shrug: So here a simplified version (no special references to fonts, colors etc in polybar).

Somewhere within the polybar configuration:
```dosini
[module/yubikey]
type = custom/ipc

hook-0 =
hook-1 = echo  " <key-icon> " # GitHub does not show NerdFont icons...

format-foreground = #ffffff
format-background = #ff0000
```

A new SystemD service unit dependent on the one provided by this project here:
```dosini
[Unit]
Description=Push YubiKey touch notifications to Polybar module for visualization
After=yubikey-touch-detector.service

[Service]
# Note the awkward offset of +1 for the correct polybar hook.
ExecStart=/bin/sh -c "ncat --unixsock $XDG_RUNTIME_DIR/yubikey-touch-detector.socket | while read -n5 message; do polybar-msg hook yubikey $((${message:4} +1)); done"

[Install]
WantedBy=yubikey-touch-detector.service
```

**Comment by maximbaz** [comment]
I'm very glad that you made it working, I linked this comment in the README, thank you for sharing it 😉

**Comment by weilbith** [comment]
Cool. I'm still on the blinking/animation part. Someone at Reddit told be it should actually work. I'll update the comment if I got it working. I think such effect would make it way better to recognize.

**Comment by weilbith** [comment]
**Update**

Polybar module without a service:

```dosini
[module/yubikey]
type = custom/script

exec = ncat --unixsock $XDG_RUNTIME_DIR/yubikey-touch-detector.socket | while read -n5 message; do [[ $message = *1 ]] && echo " <key-icon> " || echo ""; done
tail = true

format-foreground = #ffffff
format-background = #ff0000
```

This should be promising to allow to apply blinking animation. The key here is the `tail = true` option. But I guess that should not be a one-liner than.

**Comment by C0DK** [comment]
For noobs like me; if you are on arch you might have to install `nmap` to get the correct version of `ncat` :)

**Comment by maximbaz** [comment]
I'm using `nc -U` from `openbsd-netcat`, works well too 😉 

A hint for Arch on how to find the correct package:

```sh
$ pacman -Fy
...

$ pacman -F usr/bin/ncat
usr/bin/ncat is owned by extra/nmap 7.80-3

$ pacman -F usr/bin/nc
usr/bin/nc is owned by extra/gnu-netcat 0.7.1-8
usr/bin/nc is owned by community/openbsd-netcat 1.217_2-1
```

**Comment by maximbaz** [comment]
Guys I thought to create Wiki for all sorts of integrations like you shared above, you should be able to edit it without any approvals, and I'm happy for the community to take charge and order Wiki however you see fit 👍 

I made an initial page, just as an example: https://github.com/maximbaz/yubikey-touch-detector/wiki/Polybar
