### ISSUE TITLE
Stdout notifier

### ISSUE THREAD

**Issue by lentinj** [maximbaz/yubikey-touch-detector#31]
Thanks for this! I'm using it to display alerts via [i3-nagbar](https://linux.die.net/man/1/i3-nagbar) with the following shell script, which is working nicely:

```
ALERT_PID=""

close_alert() {
    [ -n "${ALERT_PID}" ] && kill "${ALERT_PID}"
    ALERT_PID=""
}
trap close_alert EXIT INT TERM

"${YTD_BIN}" -v 2>&1 | grep --line-buffered -oP '(?<=\[notifiers/stdout\] )[^"]*' | while read -r L; do
    close_alert
    if [ "${L}" = "GPG_1" ] || [ "${L}" = "U2F_1" ]; then
        i3-nagbar -m "${L}: Press the Yubikey button" 2>/dev/null &
        ALERT_PID="$!"
    fi
done
```

This is too ugly for the wiki as-is though---parsing the debug output to extract messages is asking for trouble.

Admittedly I could use the systemd units and read from the unix socket like [waybar-yubikey](https://github.com/maximbaz/dotfiles/blob/master/.local/bin/waybar-yubikey#L14), but feels like needless complexity when my script could start it up for me. Would you be interested in a stdout notifier, activated with ``yubikey-touch-notifier --stdout`` that could go straight into a while loop like the above? Or is there reasoning behind the unix socket that I've missed?

Another minor point, ["notifiers/stdout"](https://github.com/maximbaz/yubikey-touch-detector/blob/main/notifier/stderr.go#L16) is a misleading name for the messages, since nothing comes out of stdout. Would you accept a pull request to change it to "notifiers/stderr" to match the notifier name? "notifiers/debug" is probably more accurate, mind.

**Comment by maximbaz** [comment]
Hello 👋 

First of all, nice! 

Yes to both 🙂 And if you can add your script to the wiki after we are done, it's also highly appreciated 🙂 

Let's rename the current one to `notifiers/debug`, and let's have an explicit `--stdout` that maps to a new `notifiers/stdout` that prints events on stdout, so it would look like below, right?

```sh
$ yubikey-touch-detector --stdout
GPG_1
GPG_0
U2F_1
U2F_0
...
```

**Comment by lentinj** [comment]
Ace! Thanks for your help!

I'll combine what I've got with your bash script, which is better at managing multiple notifications than what I'm doing ATM, and add it to the wiki.
