### ISSUE TITLE
Feature Request: Configurable notification text

### ISSUE THREAD

**Issue by Nate-Wilkins** [maximbaz/yubikey-touch-detector#36]
It's nice that I get a notifications now when requesting authorization.

However, it would be cool to have the ability to customize that message as well.

I'm not a golang programmer but I might be able to implement something.
Looks like [this line](https://github.com/maximbaz/yubikey-touch-detector/blob/916faea86ca3932ae096a7f03ec86f6a1845394a/notifier/libnotify.go#L37) would need the configuration. 

Possibly pulling from the systemd config file? Not sure.

Happy Holidays!

**Comment by maximbaz** [comment]
Hello, configuring notifications was intentionally left out of scope for the project, please see for example https://github.com/maximbaz/yubikey-touch-detector/issues/34, it's super easy to customize it outside of the source code, and you can add whatever you want, including custom text, title, sound, icon and whatnot 🙂

**Comment by Nate-Wilkins** [comment]
Wow I can't use the issues search apparently! I'll close this out in favor of #34. 

Thanks again for this library its very helpful.
