### ISSUE TITLE
Install on Debian

### ISSUE THREAD

**Issue by williamdes** [maximbaz/yubikey-touch-detector#37]
Using the next Debian 12.

```sh
# untar to some place, like /tmp
sudo mv /tmp/yubikey-touch-detector-1.10.0-linux64/yubikey-touch-detector /usr/bin/yubikey-touch-detector
mv /tmp/yubikey-touch-detector-1.10.0-linux64/yubikey-touch-detector.service ~/.config/systemd/user/yubikey-touch-detector.service
mv /tmp/yubikey-touch-detector-1.10.0-linux64/yubikey-touch-detector.socket ~/.config/systemd/user/yubikey-touch-detector.socket

# Config
# See: https://superuser.com/a/365918/609233
mkdir -v ${XDG_CONFIG_HOME:-$HOME/.config}/yubikey-touch-detector/
nano ${XDG_CONFIG_HOME:-$HOME/.config}/yubikey-touch-detector/service.conf
# Enable desktop notifications: https://github.com/maximbaz/yubikey-touch-detector#configuring-the-app

# Register service and start it
systemctl --user daemon-reload
systemctl --user enable --now yubikey-touch-detector.service
# Check running
systemctl --user status yubikey-touch-detector.service
# Cleanup
rm -r /tmp/yubikey-touch-detector-1.10.0-linux64/
```

You can add this to the README

**Comment by maximbaz** [comment]
Thanks for sharing. This looks quite similar to how you install any application on Linux, may I ask what was the most unintuitive part of the installation?

**Comment by williamdes** [comment]
> Thanks for sharing. This looks quite similar to how you install any application on Linux, may I ask what was the most unintuitive part of the installation?

the part where I had to research where to put service files and what value XDG_CONFIG_HOME was ^^

also, the notification has no icon, it's a bit ugly

**Comment by maximbaz** [comment]
I think this belongs to wiki, as location of systemd files and XDG environment variables aren't really something this project decides 😊 Feel free to create a page on wiki though, it's fully editable by anyone! 

The notification is a demo, and you'll see both in other closed issues and maybe on wiki that the preferred approach is to build your own notification mechanism - it's very easy!

**Comment by williamdes** [comment]
> I think this belongs to wiki, as location of systemd files and XDG environment variables aren't really something this project decides blush Feel free to create a page on wiki though, it's fully editable by anyone!
> 
> The notification is a demo, and you'll see both in other closed issues and maybe on wiki that the preferred approach is to build your own notification mechanism - it's very easy!

Hi @maximbaz 
Thank you for your nice comment !
I am currently crowded with work, so it's best if you can create the wiki page and I can review and do adjustments if needed
Keeping this open so it's done one day by myself or somebody :)

**Comment by williamdes** [comment]
I should make an article on my blog 😄 
Totally forgot about this issue.

FYI: I did open a MR to update the package on Alpine Linux.
See: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/59741

Are you aware that some platforms do not build ?
```sh
arch="all !armhf !armv7 !x86"  # fails to build
```

**Comment by williamdes** [comment]
Edit: the new version seems to build on all arches 🎉 
See: https://gitlab.alpinelinux.org/williamdes/aports/-/pipelines/210110

**Comment by maximbaz** [comment]
I'll close the ticket since it seems like there's no pending action - as for the wiki, it's open for anyone, so whoever wants to write something, do not hesitate :wink:

**Comment by maximbaz** [comment]
Hello, the `yubikey-touch-detector-1.12.5.tar.gz` can be downloaded if you press `Source code (tar.gz) ` button that Github auto-adds to every release - it's not a pre-built binary though, just the source code.

I don't have an x86-64 system in order to build the binaries... The way to go about it would be to configure CI to auto-build and attach binaries for all kinds of platforms, but I never got around to do that. Help is welcome :)

**Comment by williamdes** [comment]
> Hello, the yubikey-touch-detector-1.12.5.tar.gz can be downloaded if you press Source code (tar.gz) button that Github auto-adds to every release - it's not a pre-built binary though, just the source code.

Okay, that's what I was thinking

> I don't have an x86-64 system in order to build the binaries... The way to go about it would be to configure CI to auto-build and attach binaries for all kinds of platforms, but I never got around to do that. Help is welcome :)

Oh, okay. I can help with this.
That will be mostly copy paste from other projects
There is a lot of GitHub actions to automate this
