### ISSUE TITLE
Add option to disable GPG detection

### ISSUE THREAD

**Issue by Majiir** [maximbaz/yubikey-touch-detector#43]
There should be an option to disable GPG detection.

As noted in https://github.com/maximbaz/yubikey-touch-detector/issues/22#issuecomment-780688870, GPG detection is a bit hacky. I am not a GPG user, so I was surprised to find that enabling `yubikey-touch-detector` caused my Yubikey LED to stay on long after each touch. It turns out that merely opening the GNOME Passwords and Keys app creates `~/.gnupg/pubring.kbx`, which `yubikey-touch-detector` then uses as evidence that the user wants the GPG check.

For consistency, it would be great to have an option for each detector method.

**Comment by maximbaz** [comment]
"a bit hacky" is an understatement :sweat_smile: Good to know that pubring.kbx can exist without gpg being installed.

Now that #44 is fixed, I don't see any reason to add 3 extra options that won't be used by anyone. Could you confirm that the app works fine out of the box for you?

**Comment by Majiir** [comment]
Yes, your patch for #44 addresses the core problem. Thanks for the quick fix!
