### ISSUE TITLE
Gracefully handle missing `gpg` in PATH

### ISSUE THREAD

**Issue by Majiir** [maximbaz/yubikey-touch-detector#44]
As described in https://github.com/maximbaz/yubikey-touch-detector/issues/43, it is possible for a user to have a `~/.gnupg/pubring.kbx` file without being a GPG user.

When `yubikey-touch-detector` finds the keyring, it enables GPG detection. Then, when there is a touch event, `yubikey-touch-detector` spams this its log:

```
ERRO[2023-09-19T21:15:28-04:00] exec: "gpg": executable file not found in $PATH 
ERRO[2023-09-19T21:15:28-04:00] exec: "gpg": executable file not found in $PATH 
ERRO[2023-09-19T21:15:28-04:00] exec: "gpg": executable file not found in $PATH 
ERRO[2023-09-19T21:15:28-04:00] exec: "gpg": executable file not found in $PATH 
ERRO[2023-09-19T21:15:28-04:00] exec: "gpg": executable file not found in $PATH
```

**Comment by maximbaz** [comment]
Thanks for the report! Definitely makes sense to skip gpg-based watchers, when there's no gpg present in `$PATH` - fixed in https://github.com/maximbaz/yubikey-touch-detector/commit/a241bcf70545821b89e9d5cc761e993a617aeae3 :+1:
