### ISSUE TITLE
`git` operations using SSH keys shadow notification

### ISSUE THREAD

**Issue by Jazzinghen** [maximbaz/yubikey-touch-detector#45]
When using yubikey-backed ssh keys to access a github repository the CLI operations do not show any notification that a touch is required.

**Comment by maximbaz** [comment]
I cannot reproduce, I generated a key using `ssh-keygen -t ed25519-sk`, added it to my github profile, cloning this repo using `git clone` and forcing this exact key, and I do get the "touch required" notification. Could you please provide repro steps?
