### ISSUE TITLE
How to circumvent `-buildmode=pie not supported on OpenBSD`

### ISSUE THREAD

**Issue by anoduck** [maximbaz/yubikey-touch-detector#55]
Admittedly, I know next to nothing in Go-lang, not even 'hello, world'. I know this is primarily designed to be run within a Linux environment as a systemd user level service, but if I could get it to build then I can always run it on startup with i3, or write up a rc.d file for it. That scenario would be awesome.

**Comment by maximbaz** [comment]
Try this: `make build GOFLAGS=-trimpath -ldflags=-linkmode=external`

**Comment by anoduck** [comment]
@maximbaz Ah, I see now. `go build` quickly returned a set of errors, where with `make build` hesitated returning stderror long enough to give the illusion it might successfully compile, but inevitably returned the same set of error messages.

``` bash
# github.com/maximbaz/yubikey-touch-detector/detector
detector/gpg.go:21:57: undefined: notify.InOpen
detector/gpg.go:21:72: undefined: notify.InDeleteSelf
detector/gpg.go:21:93: undefined: notify.InMoveSelf
detector/gpg.go:33:15: undefined: notify.InOpen
```
Oh, drat. I have to upgrade my system, so I can upgrade to the newest release of gpgme. So, here goes an hour of updates.

**Comment by anoduck** [comment]
@maximbaz Even after a fresh upgrade to the newest release of distribution packages, the same error is returned. 

Unless you have anything to add, I am going to go close this one out, and perhaps will return to it someday. The project provides a missing feature to the YubiKey ecosystem that, IMHO, is difficult to see how anyone could have overlooked the necessity of. On my desktop, the YubiKey touch indicator is blocked from view by other USB devices, and unless I know to look for the indicator, I would never normally notice if it flashed or not. In other words, it is a brilliant project and well implemented. I applaud your creativity.

**Comment by maximbaz** [comment]
Thanks for the kind words! I've never used OpenBSD myself, but from what I could read, it doesn't have `inotify` system, that this project uses for certain detections. The good news is that there seems to exist a similar system called `kqueue`, which might be possible to use instead.

Code-wise, we can abstract away the necessary filesystem watches in a separate file/package, and have two different implementations, one for Linux using `inotify` and another for BSD using `kqueue` - a very simplistic example is [`openbsd` folder in this repo](https://github.com/browserpass/browserpass-native/tree/master/openbsd).

This requires thought that someone using OpenBSD would implement this, to see and prove that `kqueue` can indeed provide the necessary events, and that detection works as expected.

We will also see where https://github.com/maximbaz/yubikey-touch-detector/issues/54 leads us, based on the reports in that thread `inotify` can no longer help us with the new `keyboxd` format, so if the solution will become non-inotify-based, it might be that it will also work for OpenBSD.

**Comment by anoduck** [comment]
@maximbaz If you need a guinea pig, I will run the wheel anytime you ask. I just don't want to ask any developer to go out of their way to create a special release of OpenBSD, and have only a handful of users. Especially when I am unfamiliar with the quantity of time needed to create a specific OS release. 

As for #54, it is one of those rare occasions when OpenBSD is actually up to speed on version releases, as my GPG version is `2.4.5`. Which places me in the version range where the keyboxd is a provided option of GPG, although I do not currently use it. It does appear though that keyboxd would provide a pathway towards creation of a cross-platform solution. Which would make it the best resolution for providing OpenBSD compatibility. Proverbially speaking, it would be hitting two birds with one stone. Very promising indeed.
