### ISSUE TITLE
.lk# files left in .gnupg

### ISSUE THREAD

**Issue by donnex** [maximbaz/yubikey-touch-detector#8]
I started to use this project a couple of days ago (really liking it). Now my `.gnupg` folder is getting filled with files like `.lk#......`.

I found https://unix.stackexchange.com/questions/246121/files-starting-with-lk0xb-in-gnupg-directory-what-are-they/246129#246129 that explains that this is lock files and that they're supposed to be cleaned up.

It seems to happen on every authentication.

Is this something `yubikey-touch-detector` should clean up or could it be something with my GPG or machine setup?

**Comment by maximbaz** [comment]
I have these files too, very annoying!

But I haven't realized until now that they might be connected to this project... But you are totally right, I've just confirmed, with yubikey-touch-disabled they do not appear!

Will take care of it, thanks for letting me know!

**Comment by maximbaz** [comment]
Let me know if `1.4.1` doesn't fix the issue for you, or it causes some other regression.

**Comment by donnex** [comment]
Wow fast response :)

I just updated to 1.4.1 (running arch) and restarted the systemd service. 
Sadly it still seems that these files are left in the folder even after upgrading.

**Comment by maximbaz** [comment]
Old files are left, but the new files should not be generated anymore. Please remove them manually one last time :slightly_smiling_face:

**Comment by donnex** [comment]
Yeah I did remove all old files before upgrading. But they still show up.

```
17 Jan 30 10:30 .#lk0x000055e408230480.MACHINE.85076
17 Jan 30 10:22 .#lk0x000055f52122d480.MACHINE.82493
17 Jan 30 11:00 .#lk0x00005296f4a4480.MACHINE.93403
17 Jan 30 10:30 .#lk0x000055fbb210a480.MACHINE.85306
```

**Comment by maximbaz** [comment]
I confirm I have them too again :disappointed: I don't feel comfortable making `yubikey-touch-detector` removing files in `~/.gnupg` because technically it's not creating them (these files are created by `gpg` binary when `yubikey-touch-detector` calls `gpg --card-status`), I'll be looking for a better solution...

**Comment by donnex** [comment]
Yeah same story here. They are still created and left in the folder.

Any ideas of how or why this keeps happening?

**Comment by maximbaz** [comment]
I know that these lines of code are calling `gpg` and killing the process, my best guess is that kill is not graceful enough or `gpg` doesn't just handle it correctly and it leaves its temporary files behind.

https://github.com/maximbaz/yubikey-touch-detector/blob/ce2c6964628abceb69ec8b7ae6f7068658e5bca4/detector/gpg.go#L54-L58

I haven't had a chance to play and see how to improve this...

**Comment by donnex** [comment]
For the moment I've solved this by using using a systemd user .path unit if someone else has the same issue.

gpg-lockfile-cleanup.path

    [Unit]
    Description=Monitor for leftover GPG lock files

    [Path]
    PathExistsGlob=%h/.gnupg/.#lk*

    [Install]
    WantedBy=default.target

gpg-lockfile-cleanup.service

    [Unit]
    Description=Remove leftover GPG lock files

    [Service]
    Type=oneshot
    ExecStartPre=/bin/sleep 20
    ExecStart=/bin/sh -c '[ -f "%h/.gnupg/.#lk"* ] || exit 0 && rm %h/.gnupg/.#lk*'

**Comment by maximbaz** [comment]
I didn't come up with any other solution, so I ended up changing my mind and removing the temporary files in code, I don't like it very much but I think it's the best we can do to solve the problem...

If you'd like to test, here's a binary: [gpg-cleanup.tar.gz](https://github.com/maximbaz/yubikey-touch-detector/files/4474675/gpg-cleanup.tar.gz)

**Comment by maximbaz** [comment]
I must sadly revert this code, I noticed that some gpg functionality gets occasionally broken because yubikey-touch-detector interferes with its temp files:

```
Delete this key from the keyring? (y/N) y
gpg: lock not made: Oops: stat of tmp file failed: No such file or directory
gpg: can't lock '/home/maximbaz/.gnupg/pubring.kbx'
gpg: deleting keyblock failed: No such file or directory
gpg: XXXXXX: delete key failed: No such file or directory
```

I must leave deleting these temp files to a user.

The only proper fix I see is to support smartcard protocol instead of doing gpg hacks, just like we did for U2F / Webauthn protocols, but unfortunately I don't know how to do it and require some help.

**Comment by donnex** [comment]
Oh .. I see.

I made a small systemd service for cleaning these files before you added cleanup to yubikey-touch-detector. I guess I'll have to go back to that solution again.

One possible, if not a very nice one, would be to clean old left over lock files if there over some threshold age? But that would require some kind of recheck 1 minute later for lock files and remove them if there still there. Could be a bit complicated since it's not really yubikey-touch-detector that leaves them if I understand correctly.

**Comment by maximbaz** [comment]
Yeah I think a cleanup service is the best course of action for now, otherwise we will drown in these hacks 😞 

Maybe this will be annoying enough for us to drive research of how to properly implement smartcard protocol 😜

**Comment by donnex** [comment]
Hehe, I'm actually using https://github.com/gopasspw/gopass ass my password manager and it's using GPG.
Would it still be possible to detect when touch is needed with proper smartcard support for GPG?

**Comment by maximbaz** [comment]
Yes, it will be monitored on a lower level, so all apps will be captured. If only I knew how to do it... 😄 But that's how U2F / Webauthn support is implemented now.

**Comment by maximbaz** [comment]
I have found a relatively clean way to remove these files periodically and documented them in the README:

https://github.com/maximbaz/yubikey-touch-detector#what-are-those-lk-files-in-gnupg-and-how-to-clean-them-up

Still hoping one day to stop producing them entirely, but decided to at least document this for easier discovery.

**Comment by pfoo** [comment]
Wouldn't gpg --lock-never option prevent those files creation ?

A quick test shows that : 
gpg --decrypt testfile.gpg          ->  .#lk0x* created
gpg --card-status                      ->  .#lk0x* created (one per process, and you launch this every second)
gpg --lock-never --card-status  -> no .#lk0x* created


That being said, it feels like a bug in gnupg considering that interrupting a decrypt operation also sometime fails to delete de lock. I'm also not understanding why the hell gnupg creates lockfile in the config directory and not in it's own temporary run directory (/run/user/{$UUID}/gnupg/ in modern distribution)

**Comment by maximbaz** [comment]
`1.9.1` is out with the fix

**Comment by maximbaz** [comment]
These files were still occasionally being created, but with `1.11.0` we have switched to `gpgme` and IPC communication, which means we are not spawning and killing `gpg` processes anymore, which _hopefully_ means this issue is _finally_ gone for good :sweat_smile:

**Comment by brvtalcake** [comment]
Just for completeness, and in case you end up having this issue again : 
As far as I understand (and after `cat`ing the content of these lockfiles + after reading [this thread](https://forum.gnupg.org/t/what-are-the-files-in-gnupghome/4174)), it might be completely ok to remove those lock files. At least after the process whose pid is written in it (at least I suppose theses are pids) has exited (or before anything needing gpg starts, e.g. as an init script, for example).
Cheers
