### ISSUE TITLE
Not detecting U2F from WebAuthn?

### ISSUE THREAD

**Issue by ChadTaljaardt** [maximbaz/yubikey-touch-detector#9]
I am unsure if i am doing something wrong here, so please bear with me. 

I started the application using the command 

`yubikey-touch-detector -v`

and i got the output here: 

```
DEBU[2020-03-07T11:11:22-05:00] Starting YubiKey touch detector
DEBU[2020-03-07T11:11:22-05:00] SSH watcher is successfully established
DEBU[2020-03-07T11:11:22-05:00] GPG watcher is successfully established
DEBU[2020-03-07T11:11:22-05:00] U2F watcher is successfully established
```

Then i went [here](https://webauthn.io/) and typed a random username and clicked `register`, then yubikey started flashing and the website showed a screen for me to touch the yubikey, however the output of the terminal didnt change. 

I am trying to integrate this with waybar, and i used the same script listed [here](https://raw.githubusercontent.com/maximbaz/dotfiles/master/bin/waybar-yubikey)

however when running this script i got a error saying the following : 

```
waybar-yubikey
nc: invalid option -- 'U'
Try `nc --help' for more information.
```

I then made a modification to make `-U` lowercase and be `-u` but then i got this error:

```
Error: Couldn't resolve host "/run/user/1000/yubikey-touch-detector.socket"
```

I have no idea how to continue, i went to that url in the browser and the socket file does exist.. so i have no idea why netcat isn't able to connect to it. Any help?

**Comment by ChadTaljaardt** [comment]
![screenshot](https://user-images.githubusercontent.com/13891249/76152619-794e8400-608f-11ea-8c08-aff92da10880.png)

**Comment by maximbaz** [comment]
Hey, thanks for reporting!

I confirm that the app does not detect it. The reason we can detect U2F when `pam` is involved in the first place is simply because I was able to tap into `pam-u2f` codebase and add some marker that yubikey-touch-detector can use.

When browsers request U2F, they don't use `pam-u2f`, so the markers don't get created. Furthermore, I'm afraid different browsers use different code for U2F communication, and there is no "common ground" such as a driver or a library where we would be able to inject some code to help us detect this event...

I'm very much open to ideas on how to detect this.

> nc: invalid option -- 'U'
> Try `nc --help' for more information.

Make sure to install openbsd version of netcat, if you are on Arch Linux, it's [openbsd-netcat](https://www.archlinux.org/packages/community/x86_64/openbsd-netcat/).

**Comment by maximbaz** [comment]
I have found a promising way to detect all U2F requests that does not depend on `pam-u2f`, will get back to you later with something to test 🙂

**Comment by ChadTaljaardt** [comment]
Thanks @maximbaz that sounds awesome.

**Comment by maximbaz** [comment]
Please test `1.5.0` and let me know if it works for you now. Also do let me know if you still struggle with waybar integration after installing `openbsd-netcat`, it works very well for me so I'd be happy to help you with this. And if everything works now, enjoy 👍

**Comment by ChadTaljaardt** [comment]
I installed the openbsd version, everything seemed to be working fine. Ill try the latest fix you have. I assume i just need to do something like 

`yay -Sy yubikey-touch-detector`

**Comment by maximbaz** [comment]
on Arch Linux I push it directly to official repos, so just `pacman -Syu` would do the trick for you as soon as your mirrors get an update 😉

**Comment by maximbaz** [comment]
After an update, if you are using systemd service, remember to restart it too

```
$ systemctl --user daemon-reload
$ systemctl --user restart yubikey-touch-detector.service
```

And then reload waybar-yubikey and waybar :)

**Comment by ChadTaljaardt** [comment]
Hmm its still not working for me for some reason..

**Comment by ChadTaljaardt** [comment]
Ahh wait im on version 1.4.1 not 1.5, need to wait for that update to come through.

**Comment by maximbaz** [comment]
A sneaky way to get it directly without waiting for mirrors to update:

```
sudo pacman -U https://archive.archlinux.org/packages/y/yubikey-touch-detector/yubikey-touch-detector-1.5.0-1-x86_64.pkg.tar.zst
```

**Comment by ChadTaljaardt** [comment]
hmm okay so i've installed the latest package, i reloaded the services and then rebooted and still not working

**Comment by ChadTaljaardt** [comment]
```
➜ yubikey-touch-detector -v
DEBU[2020-03-08T18:29:40-04:00] Starting YubiKey touch detector
DEBU[2020-03-08T18:29:40-04:00] SSH watcher is successfully established
DEBU[2020-03-08T18:29:40-04:00] U2F watcher on '/dev' is successfully established
DEBU[2020-03-08T18:29:40-04:00] GPG watcher is successfully established
ERRO[2020-03-08T18:29:45-04:00] Cannot establish a watch on folder '/dev/hidraw4': permission denied
DEBU[2020-03-08T18:29:46-04:00] U2F watcher on '/dev/hidraw5' is successfully established
DEBU[2020-03-08T18:29:51-04:00] [notifiers/stdout] U2F_1
DEBU[2020-03-08T18:29:55-04:00] [notifiers/stdout] U2F_0
^C
DEBU[2020-03-08T18:30:00-04:00] Stopping YubiKey touch detector
```

**Comment by ChadTaljaardt** [comment]
```➜ systemctl --user status yubikey-touch-detector.service
● yubikey-touch-detector.service - Detects when your YubiKey is waiting for a touch
     Loaded: loaded (/usr/lib/systemd/user/yubikey-touch-detector.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2020-03-08 18:30:56 EDT; 39s ago
   Main PID: 2416 (yubikey-touch-d)
     CGroup: /user.slice/user-1000.slice/user@1000.service/yubikey-touch-detector.service
             └─2416 /usr/bin/yubikey-touch-detector

Mar 08 18:30:56 archlinux systemd[675]: Started Detects when your YubiKey is waiting for a touch.
Mar 08 18:31:01 archlinux yubikey-touch-detector[2416]: time="2020-03-08T18:31:01-04:00" level=error msg="Cannot establish a watch on folder '/dev/hidraw4': permission denied"
```

**Comment by ChadTaljaardt** [comment]
so when i start it manually using the command, it seems to work fine, when i start it with the service, it seems to get stuck on that error.

**Comment by maximbaz** [comment]
I don't think that error is anything significant really, but we could fix it as well - could you run this command below for every `/dev/hidraw*` file you have, and tell me which of them contain "YubiKey"?

```
$ cat /sys/class/hidraw/hidraw<N>/device/uevent
```

How do you test the service, with waybar? Make sure you are restarting the `waybar-yubikey` and then `waybar` processes.

**Comment by ChadTaljaardt** [comment]
Ahh i think i had forgot to restart the waybar process.. did that and it worked. then i rebooted and tried it again as soon as it started up and it worked again!

Thanks so much for this, i really appreciate it!

**Comment by maximbaz** [comment]
Awesome! Happy to help, enjoy, and thanks for even letting me know about WebAuthn 😄

**Comment by maximbaz** [comment]
@ChadTaljaardt would you be able to test U2F detection in this binary? It's a complete rewrite of U2F/FIDO2 support that doesn't depend on any file watcher hacks, but properly reading HID device according to the spec. Thanks!

[new-u2f.tar.gz](https://github.com/maximbaz/yubikey-touch-detector/files/4506663/new-u2f.tar.gz)
